# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-09 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('prize', models.IntegerField()),
                ('pages', models.IntegerField()),
            ],
        ),
    ]
